[build]
  command  = "npm run build"
  publish  = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
  included_files = ["server/**"]
  node_version = "18"

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Статика на год
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# SW — без кэша
[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"

# Безопасные заголовки + более либеральный CSP для запуска
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Content-Security-Policy = """
  default-src 'self';
  base-uri 'self';
  object-src 'none';
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://checkout.stripe.com blob:;
  style-src 'self' 'unsafe-inline';
  img-src 'self' data: blob: https:;
  font-src 'self' data:;
  connect-src 'self' https://*.supabase.co https://*.supabase.in https://api.stripe.com https://checkout.stripe.com;
  frame-src https://js.stripe.com https://checkout.stripe.com;
  worker-src 'self' blob:;
  form-action 'self' https://checkout.stripe.com;
  """
