[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888

# API → функции (общее правило)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback — в самом конце и БЕЗ force
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # эти ключи публичные (и MAIL_FROM шаблонный) — не считаем секретами
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY,MAIL_FROM"
