name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run -s typecheck || echo "no typecheck script"

      - name: Lint
        run: npm run -s lint || echo "no lint script"

      - name: Test
        run: npm run -s test:run || echo "no tests"

      - name: Build
        run: npm run -s build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: mira-dist
          path: dist
